### ISSUE TITLE
模型转换的疑问

### ISSUE THREAD

**Issue by huangzhenjie** [msnh2012/Msnhnet#108]
您好，这个项目非常好，我想请教下，不支持的op怎么添加吗？

**Comment by msnh2012** [comment]
你好，有哪些OP需要转换，模型最好是用pytorch原生的一些操作，尽量减少一些+-之列的拼凑

**Comment by huangzhenjie** [comment]
就是比如一些后处理操作，比如维度的广播对齐，切片，升维降维，逻辑运算符之类的

**Comment by msnh2012** [comment]
后处理多么？不多的话可以自己实现下

**Comment by huangzhenjie** [comment]
就是这些都是不支持转出来的吧

**Comment by huangzhenjie** [comment]
好的，非常感谢
