### ISSUE TITLE
any benchmark of msnhnet vs popular DL framework?

### ISSUE THREAD

**Issue by alanzhai219** [msnh2012/Msnhnet#109]

**Comment by msnh2012** [comment]
Nope, just for own use.(Due to lack of time) As for speed, same as darknet.

**Comment by alanzhai219** [comment]
> Nope, just for own use.(Due to lack of time) As for speed, same as darknet.

Is there any plan to optimize performance for the native impls?

**Comment by msnh2012** [comment]
I'm concentrating on robot algos recently. May be later.

**Comment by alanzhai219** [comment]
> I'm concentrating on robot algos recently. May be later.

Got it. Thanks.
