### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by YuDe95** [msnh2012/Msnhnet#113]
### evn:build in vs2019 cuda10.2.  win10 GPU GTX960X
1.when i build msnhnet it occurs error in function https://github.com/msnh2012/Msnhnet/blob/4e09f2501ba8db789f0a20441a357de3ba468f10/src/layers/cuda/MsnhActivationsGPU.cu#L66
use foor is error ,so i change foorf function.
2.when i use cmake msnhnetviewer don't add lib msnhnet.lib and cudnn.lib in this project.

**Comment by msnh2012** [comment]
You'd better to build msnhnetviewer with cpu mode.
