### ISSUE TITLE
Fps of deeplabv3

### ISSUE THREAD

**Issue by John-Yao** [msnh2012/Msnhnet#36]
Hi, thanks for your great work!
I am interested in the fps of deeplabv3. Could you provide some detail how to test the fps of deeplabv3, such as image size, and the fps of pytorch version.
Thanks

**Comment by BBuf** [comment]
You can know its FPS by running demo of deeplabv3，example code is here : https://github.com/msnh2012/Msnhnet/blob/master/examples/deeplabv3_gpu/deeplabv3_gpu.cpp , just compile and run it。

**Comment by John-Yao** [comment]
Thanks for your reply!
But I still cannot figure out the image size for testing image from the provided code.

**Comment by msnh2012** [comment]
![image](https://user-images.githubusercontent.com/17841334/93040197-fa5c8880-f67b-11ea-9412-98497f5d584a.png)

**Comment by John-Yao** [comment]
I got it, Thanks!
