### ISSUE TITLE
编译出现error C3861: “_mm256_extract_epi64”: 找不到标识符

### ISSUE THREAD

**Issue by mkwml** [msnh2012/Msnhnet#4]
在使用vs2015编译时出现这个问题？Msnhnet\include\Msnhnet/core/MsnhGemm.h(182): error C3861: “_mm256_extract_epi64”: 找不到标识符，我电脑配置是I7-7700。编译选项，openmp、open_blas、qt选项都关闭了。谢谢

**Comment by msnh2012** [comment]
使用VS2017以上试试

**Comment by mkwml** [comment]
> 使用VS2017以上试试

是的，我用vs2019编译成功了，谢谢~
