### ISSUE TITLE
win10 vs2019上面一直编译失败

### ISSUE THREAD

**Issue by fangzong12** [msnh2012/Msnhnet#7]
error 1：error C3861: “_mm256_cvtss_f32”: 找不到标识符
error 2：error C3861: “_mm256_extract_epi64”: 找不到标识符
error 3：无法打开包括文件: “yaml-cpp/yaml.h”: No such file or directory

warming 1: warning C4752: 发现 Intel(R) 高级矢量扩展；请考虑使用 /arch:AVX

可否提供一份详细的，傻瓜式的编译教程，非常感谢

还有我在ubuntu上编译成功了，没有看到MnshnetViewer工具

**Comment by fangzong12** [comment]
ps: 整个流程是按照readme完成的

**Comment by msnh2012** [comment]
https://github.com/msnh2012/Msnhnet/blob/master/ReadMe_CN.md这里有详细教程

**Comment by msnh2012** [comment]
https://github.com/msnh2012/Msnhnet/blob/master/ReadMe_CN.md
这里有详细教程.

**Comment by msnh2012** [comment]
视频教程

**Comment by fangzong12** [comment]
谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "msnh2012/Msnhnet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 下午4:30
收件人:&nbsp;"msnh2012/Msnhnet"<Msnhnet@noreply.github.com&gt;;
抄送:&nbsp;"非语"<543667301@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [msnh2012/Msnhnet] win10 vs2019上面一直编译失败 (#7)





 
https://github.com/msnh2012/Msnhnet/blob/master/ReadMe_CN.md
 这里有详细教程.

**Comment by BBuf** [comment]
你的cpu可能不支持avx，用cpu-z查一下吧

**Comment by fangzong12** [comment]
好的，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "msnh2012/Msnhnet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月24日(星期一) 下午4:31
收件人:&nbsp;"msnh2012/Msnhnet"<Msnhnet@noreply.github.com&gt;;
抄送:&nbsp;"非语"<543667301@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [msnh2012/Msnhnet] win10 vs2019上面一直编译失败 (#7)





 
你的cpu可能不支持avx，用cpu-z查一下吧

**Comment by fangzong12** [comment]
i7-8700应该支持把 。。。。我对着视频教程试一下
