### ISSUE TITLE
compile faile

### ISSUE THREAD

**Issue by Lewis-luo** [msnh2012/Msnhnet#91]
![image](https://user-images.githubusercontent.com/22047229/102735089-73a30000-437c-11eb-9dd8-a0003d41eba8.png)

**Comment by Lewis-luo** [comment]
make[2]: *** Waiting for unfinished jobs....
In file included from /usr/include/c++/5/chrono:35:0,
                 from /home/lfb/Msnhnet/include/Msnhnet/config/MsnhnetCfg.h:7,
                 from /home/lfb/Msnhnet/include/Msnhnet/config/MsnhnetCuda.h: ,
                 from /home/lfb/Msnhnet/include/Msnhnet/core/cuda/MsnhBlasGPU.h:5,
                 from /home/lfb/Msnhnet/src/core/cuda/MsnhBlasGPU.cu:1:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \

**Comment by msnh2012** [comment]
Please list your platform

**Comment by Lewis-luo** [comment]
ubuntu16.4
opencv 3.4.6
GPU GTX 1080
cuda 10.2

**Comment by msnh2012** [comment]
And your cmake version?

**Comment by Lewis-luo** [comment]
cmake version 3.16.20191024-g490da0b

**Comment by msnh2012** [comment]
I’ve fixed some bugs, your can try new version.

**Comment by Lewis-luo** [comment]
Thank you very much！



---Original---
